apiVersion: v1
kind: Service
metadata:
  name: {{ include "gradio-vlm-chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gradio-vlm-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http-gradio
      protocol: TCP
      name: http
  selector:
    {{- include "gradio-vlm-chart.selectorLabels" . | nindent 4 }}