apiVersion: v2
name: gradio-vlm-chart
description: A Helm chart for deploying the Gradio VLM streaming demo application on HPE PCAI.
type: application

# This is the chart version. This is incremented for chart changes.
version: 0.1.0

# This is the version number of the application being deployed.
appVersion: "0.0.1"